### ISSUE TITLE
ROS2 aarch64 Ubuntu Bionic Build Unstable

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-oncall#10]
All builds have test failures:

* [Debug](https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/1019/#showFailuresLink)
* [Release](https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_release/981/#showFailuresLink)
* [Packaging](https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/1026/#showFailuresLink)

**Comment by zmichaels11** [comment]
Unstable: Packaging
Debug and Release are currently passing

**Comment by emersonknapp** [comment]
The Debug and Release builds are stable now, packaging's remaining issue is https://github.com/ros-tooling/aws-oncall/issues/4 - closing this issue in favor of the ros1_bridge test failure specific issue
