### ISSUE TITLE
Linux AARCH64 Packaging unstable

### ISSUE THREAD

**Issue by zmichaels11** [ros-tooling/aws-oncall#101]
## Required Information

* **Job Home**: https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/
* **First Failing Build**: https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/1146/
* **Latest Failing Build**: https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/1155/
* **External tracking ticket**: <Create a ticket on the relevant repository to report the issue to the maintainers. If that's not appropriate for this issue explain why here>

**Comment by mm318** [comment]
Stable as of at least build 1241: https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/1241/
