### ISSUE TITLE
Add E2E test to colcon-setup-python-py

### ISSUE THREAD

**Issue by zmichaels11** [ros-tooling/aws-oncall#103]
## Overview
`colcon-setup-py` needs an automated E2E test to verify that it doesn't fail when `colcon build` is ran on a pure Python module.

## Completion Criteria
- [ ] Create an E2E test for `colcon-python-setup-py` that runs `colcon build` on a pure Python module
- [ ] Create a GitHub workflow to run the build periodically (using APT and pip) and with PR.

**Comment by emersonknapp** [comment]
Closing in favor of internal tracking
