### ISSUE TITLE
Everything is failing due to OSRF Jenkins plugin update

### ISSUE THREAD

**Issue by zmichaels11** [ros-tooling/aws-oncall#104]
## Overview
All jobs built by ci.ros2.org will fail 

## Required Information
* **Job Home**: <e.g. https://ci.ros2.org/view/nightly/job/nightly_win_deb/, e.g. not a numbered build>
* **First Failing Build** (or oldest/old-ish one with this issue that you can find, best effort): 
* **Latest Failing Build** (try to keep this up to date): 
* **External tracking ticket**: <Create a ticket on the relevant repository to report the issue to the maintainers. If that's not appropriate for this issue explain why here>

**Comment by zmichaels11** [comment]
OSRF is working on the issue.
aws-oncall will continue to track this issue here.

**Comment by zmichaels11** [comment]
The issue should be resolved once https://github.com/ament/ament_lint/pull/220 is merged in

**Comment by chapulina** [comment]
The PR has been merged. Here's a test build running: https://ci.ros2.org/job/ci_linux/9602/console

**Comment by zmichaels11** [comment]
Builds are passing again.
