### ISSUE TITLE
Add APT installed colcon to colcon-bundle matrix

### ISSUE THREAD

**Issue by zmichaels11** [ros-tooling/aws-oncall#105]
## Overview
`APT` installed `colcon` should be added to the test matrix on [colcon bundle](https://github.com/colcon/colcon-bundle) to quicken triaging of broken builds. In theory, `colcon-bundle` passing in `APT` but failing in `PIP` would indicate that the build broke due to upstream changes in `colcon`.

## Completion Criteria
- [ ] Add `APT` installed `colcon` to test matrix
- [ ] Tests using `APT` should run periodically and on PR.

This issue is tracking: https://github.com/colcon/colcon-bundle/issues/150

**Comment by emersonknapp** [comment]
Closing in favor of internal tracking
