### ISSUE TITLE
armhf Ubuntu Bionic Debug | Release | Packaging Build Failure	

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-oncall#106]
## Required Information

* **Job Home**: https://ci.ros2.org/view/nightly/job/nightly_linux-armhf_debug/, https://ci.ros2.org/view/nightly/job/nightly_linux-armhf_release/, https://ci.ros2.org/view/packaging/job/packaging_linux-armhf/
* **First Failing Build** (or oldest/old-ish one with this issue that you can find, best effort): https://ci.ros2.org/view/nightly/job/nightly_linux-armhf_debug/425/console
* **Latest Failing Build** (try to keep this up to date): https://ci.ros2.org/view/nightly/job/nightly_linux-armhf_debug/434/
* **External tracking ticket**:  N/A, investigate why the build is first failing

**Comment by dabonnie** [comment]
Appears to be related to the switch to focal and dist, as previous builds with bionic are only unstable and not failing, e.g. not failing

```03:30:37 + [ bionic = focal ]
03:30:37 + [ bionic = bionic ]
03:30:37 + export CI_ROS1_DISTRO=melodic
```

and failing

```
00:30:13 + [ focal = focal ]
00:30:13 + export CI_ROS1_DISTRO=noetic
```

The silent switch was brought up during the OSRF weekly review, they said will work on messaging .

**Comment by prajakta-gokhale** [comment]
This is still failing due to the switch to Ubuntu Focal.

**Comment by thomas-moulard** [comment]
Closing as part of ops process changes.
