### ISSUE TITLE
ROS2 Windows Build Failing

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-oncall#12]
See [link](https://ci.ros2.org/view/nightly/job/nightly_win_deb/1447/)

**Comment by dabonnie** [comment]
Contacted @nuclearsandwich concerning failed builds due to [link](https://ci.ros2.org/view/nightly/job/nightly_win_deb/1447/console#console-section-37).

**Comment by dabonnie** [comment]
Windows builds are now (back) to unstable.

**Comment by dabonnie** [comment]
Windows builds back to red :-( via

* [nightly](https://ci.ros2.org/view/nightly/job/nightly_win_deb/1450/)
* [ci](https://ci.ros2.org/job/ci_windows/)

@nuclearsandwhich can you please take a look? FYI @prajakta-gokhale

**Comment by nuclearsandwich** [comment]
>     * [](https://ci.ros2.org/job/ci_windows/)
> 
> 
> @nuclearsandwich can you please take a look

Last night's nightlies were affected by an instance of https://github.com/ros2/build_cop/issues/161 on our host `portable`. A similar issue was affecting the `windshield` host. CI for mac and Windows is also currently offline due to power availability where the machines are located.

**Comment by prajakta-gokhale** [comment]
Debug build is still failing with a permission error:

```bash
04:12:48 PermissionError: [WinError 5] Access is denied: 'c:\\python37\\lib\\site-packages\\~.mpy\\core\\_multiarray_umath.cp37-win_amd64.pyd'
04:12:48 <== '"C:\Python37\python_d.exe" -m pip uninstall -y cryptography lxml numpy' exited with return code '2'
04:12:48 
```

**Comment by prajakta-gokhale** [comment]
@nuclearsandwich is there an update on fixing the Windows servers? Seems like the [Release](https://ci.ros2.org/view/nightly/job/nightly_win_rel/1389/console) nightly build failed again becuase of `PermissionError`.

**Comment by piraka9011** [comment]
Another Pip issue...

**Comment by zmichaels11** [comment]
Unstable: Debug, Packaging
Failing: Release

**Comment by zmichaels11** [comment]
Unstable: Debug, Release, Packaging

**Comment by emersonknapp** [comment]
I am closing this issue in favor of newly created more specific tracking issues
https://github.com/ros-tooling/aws-oncall/issues/64
https://github.com/ros-tooling/aws-oncall/issues/65
https://github.com/ros-tooling/aws-oncall/issues/66
