### ISSUE TITLE
Linux AARCH64 Debug build unstable

### ISSUE THREAD

**Issue by mm318** [ros-tooling/aws-oncall#120]
## Overview

21 tests are failing.

## Required Information

* **Job Home**: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/
* **First Failing Build**: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/1201/
* **Latest Failing Build**: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/1218/
* **External tracking ticket**: TBD

**Comment by thomas-moulard** [comment]
Closing as part of ops process changes.
