### ISSUE TITLE
OSX Packaging build unstable

### ISSUE THREAD

**Issue by mm318** [ros-tooling/aws-oncall#123]
## Overview

Warning in CMakeFile of 3rd party library:
```
CMake Warning (dev) at /usr/local/lib/cmake/assimp-5.0/assimpTargets.cmake:54 (if):
  if given arguments:

    "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
```

## Required Information

* **Job Home**: https://ci.ros2.org/view/packaging/job/packaging_osx/
* **First Failing Build**: https://ci.ros2.org/view/packaging/job/packaging_osx/1860/
* **Latest Failing Build**: https://ci.ros2.org/view/packaging/job/packaging_osx/1863/
* **External tracking ticket**: TBD

**Comment by thomas-moulard** [comment]
Closing as part of ops process changes.
