### ISSUE TITLE
Windows Packaging build failing

### ISSUE THREAD

**Issue by mm318** [ros-tooling/aws-oncall#124]
## Overview

Unable to find `tinyxml2`:
```
CMake Error at CMakeLists.txt:61 (add_library):
  Target "rosbag2_transport_py" links to target "tinyxml2::tinyxml2" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```

## Required Information

* **Job Home**: https://ci.ros2.org/view/packaging/job/packaging_windows/
* **First Failing Build**: https://ci.ros2.org/view/packaging/job/packaging_windows/1744/
* **Latest Failing Build**: https://ci.ros2.org/view/packaging/job/packaging_windows/1750/
* **External tracking ticket**: TBD

**Comment by thomas-moulard** [comment]
Closing as part of ops process changes.
