### ISSUE TITLE
setup-ros-docker build failing (can't find ros-foxy-ros-base)

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-oncall#127]
## Overview

It appears that the `ros-foxy-ros-base` package (nor other variants) are present in the ros2-testing repositories that we're using for Foxy CI.

http://packages.ros.org/ros2-testing/ubuntu/dists/focal/main/binary-amd64/Packages - see here, at the time of reporting this, the package is not in there.

Latest build https://github.com/ros-tooling/setup-ros-docker/runs/800088760?check_suite_focus=true

**Comment by dabonnie** [comment]
Latest builds back to green, but some recent failures when attempting to push. See 

 - https://github.com/ros-tooling/setup-ros-docker/actions/runs/152977533
 - https://github.com/ros-tooling/setup-ros-docker/runs/823189666?check_suite_focus=true

**Comment by piraka9011** [comment]
Latest runs are no longer failing since ros-tooling/setup-ros-docker#16 and for the last 5 days.
