### ISSUE TITLE
clang-libcxx has build warnings

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-oncall#130]
## Overview

The build is working again, but its success reveals to us 29 build warnings.

* 2 from rmw_fastrtps
* 26 from upstream spdlog
* 1 from ros2/demos/pendulum_control

The spdlog warnings seem to be all about int signedness implicit conversions. From the release notes for 1.6 https://github.com/gabime/spdlog/releases/tag/v1.6.0 this seems to have been fixed, it looks like they adopted using clang-tidy. spdlog_vendor currently downloads v1.5. If this resolves the 26 warnings, then the remainder should be very easy to knock out.

## Required Information

* **Job Home**: https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx
* **First Failing Build** https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/468/
* **Latest Failing Build** (try to keep this up to date): https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/468/
* **External tracking ticket**: Most issues are coming from outside the ros2 source tree and may be fixed upstream

**Comment by emersonknapp** [comment]
Trying with spdlog 1.6 to see if that fixes most of the warnings [![Build Status](https://ci.ros2.org/buildStatus/icon?job=nightly_linux_clang_libcxx&build=469)](https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/469/)

**Comment by piraka9011** [comment]
Opened https://github.com/ros2/demos/pull/459 to resolve the `pendulum_control` deprecation warning.

**Comment by emersonknapp** [comment]
This has been resolved
