### ISSUE TITLE
launch_ros_sandbox  and action-ros-ci build failing

### ISSUE THREAD

**Issue by snehaldb90** [ros-tooling/aws-oncall#139]
## Overview

launch_ros_sandbox and action-ros-ci build are failing for macOS because of test_pep257 failure.

## Required Information
For launch_ros_sandbox build
* **Job Home**: [https://github.com/ros-tooling/launch_ros_sandbox/actions](https://github.com/ros-tooling/launch_ros_sandbox/actions)
* **First Failing Build** : [https://github.com/ros-tooling/launch_ros_sandbox/actions/runs/168718465](https://github.com/ros-tooling/launch_ros_sandbox/actions/runs/168718465)
* **Latest Failing Build**: [https://github.com/ros-tooling/launch_ros_sandbox/actions/runs/168985648](https://github.com/ros-tooling/launch_ros_sandbox/actions/runs/168985648)
* **External tracking ticket**: N/A

For action-ros-ci
* **Job Home**: [https://github.com/ros-tooling/action-ros-ci/actions](https://github.com/ros-tooling/action-ros-ci/actions)
* **First Failing Build** : [https://github.com/ros-tooling/action-ros-ci/actions/runs/168718690](https://github.com/ros-tooling/action-ros-ci/actions/runs/168718690)
* **Latest Failing Build**: [https://github.com/ros-tooling/action-ros-ci/actions/runs/168985880](https://github.com/ros-tooling/action-ros-ci/actions/runs/168985880)
* **External tracking ticket**: N/A

**Comment by emersonknapp** [comment]
https://github.com/ament/ament_lint/pull/241 <- this PR added a Python3.8 feature, which is what is breaking launch_ros_sandbox, and the MacOS build on action-ros-ci

See the above PR for the Linux fixes for action-ros-ci

Windows failure on action-ros-ci not yet determined

**Comment by snehaldb90** [comment]
Failing on windows due to same pep257 error.

**Comment by snehaldb90** [comment]
Closing this ticket because the builds are passing and the error was fixed by [PR (remove use of "extend" action in argparse)](https://github.com/ament/ament_lint/pull/262)
