### ISSUE TITLE
Some of the builds fails due to flakiness

### ISSUE THREAD

**Issue by snehaldb90** [ros-tooling/aws-oncall#142]
## Overview

Check the builds 'action-ros-ci', 'setup-ros', and 'rosbag2_bag_v2'. 
They fail due to 'rosdep update' error.
https://github.com/ros-tooling/action-ros-ci/runs/891286793?check_suite_focus=true

## Completion Criteria

Builds should not fail due to flakiness.

**Comment by emersonknapp** [comment]
Closing due to not being fully actionable - will keep an eye on flaky builds
