### ISSUE TITLE
Automate build failure tickets

### ISSUE THREAD

**Issue by thomas-moulard** [ros-tooling/aws-oncall#28]
We should probably get an action to run every 10 minutes, and create issues if something is failling.
With an appropriate naming scheme, we can also handle deduplication IMHO.
https://www.npmjs.com/package/jenkins-api

**Comment by piraka9011** [comment]
@nuclearsandwich Thoughts on providing us with a username/API Token?

**Comment by nuclearsandwich** [comment]
> Thoughts on providing us with a username/API Token?

Team members who have access to create CI may already create API tokens in Jenkins. You break it you buy it.

**Comment by emersonknapp** [comment]
It seems like it may be more useful to use human pattern matching to track problems rather than builds. E.g. tickets for warnings, test failures as separate tickets so we can track external issues that we open. That's my 2c

**Comment by emersonknapp** [comment]
With that in mind, I'm going to close this for now and we can reopen if somebody has a different strong opinion
