### ISSUE TITLE
Release Colcon Bundle

### ISSUE THREAD

**Issue by piraka9011** [ros-tooling/aws-oncall#39]
We need to release the [colcon/colcon-bundle](https://github.com/colcon/colcon-bundle) package to be widely available via (TODO: Bloom/Pypi?).

**Comment by emersonknapp** [comment]
Noting that it's unclear what the resolution is here - a new release version of colcon-bundle? (would be 0.19)

**Comment by emersonknapp** [comment]
I will close this ticket until we have a concrete request to release colcon-bundle
