### ISSUE TITLE
rosbag2 compression tests fail on armhf

### ISSUE THREAD

**Issue by piraka9011** [ros-tooling/aws-oncall#53]
rosbag2 compression tests are [failing on armhf](https://ci.ros2.org/view/nightly/job/nightly_linux-armhf_debug/346/testReport/junit/rosbag2_compression/CompressionHelperFixture/zstd_decompress_fails_on_bad_file/).
The tests pass on all other systems.
It looks like there's an issue with reading file path introduced when removing filesystemhelper in rosbag2.

**Comment by thomas-moulard** [comment]
@piraka9011 I think we should have a bug in rosbag2.

**Comment by zmichaels11** [comment]
Is this issue related: https://github.com/ros2/rosbag2/issues/153

**Comment by piraka9011** [comment]
Potentially, but this looks like an issue related to compression + the fact that the bug started popping up after rosbag2's filesystem_helper was refactored to use rcpputils'.

**Comment by zmichaels11** [comment]
Resolved by https://github.com/ros2/rosbag2/pull/285
