### ISSUE TITLE
Update Github Action Version for action-ros-ci and setup-ros

### ISSUE THREAD

**Issue by piraka9011** [ros-tooling/aws-oncall#57]
action-ros-ci and setup-ros recently release and important fix in version 0.0.13 and have also been renamed. 
All packages that use these actions should be updated accordingly.

## Packages

* [rosbag2](https://github.com/ros2/rosbag2)
* [rosbag2_bag_v2](https://github.com/ros2/rosbag2_bag_v2)
* ~~[cross-compile](https://github.com/ros-tooling/cross_compile)~~ (doesn't use `action-ros-ci` nor `setup-ros`)
* [file-talker](https://github.com/ros-tooling/file_talker)
* [launch-ros-sandbox](https://github.com/ros-security/launch_ros_sandbox)
* [rcpputils](https://github.com/ros2/rcpputils)

**Comment by zmichaels11** [comment]
- [ ] rosbag2 linting PR: https://github.com/ros2/rosbag2/pull/264

**Comment by zmichaels11** [comment]
`rosbag2_bag_v2` build&test failed with "ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_argcomplete.argcomplete_completer.catkin_cmake_args': The 'catkin-pkg' distribution was not found and is required by the application"

**Comment by piraka9011** [comment]
All GH Actions have been updated.
