### ISSUE TITLE
Windows Nightly Debug build has many test failures

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-oncall#64]
## Overview

The nightly Windows Debug build has 76 test failures as of last night. It's been like this a long time apparently.

Build 1000 was passing https://ci.ros2.org/view/nightly/job/nightly_win_deb/1000/
By 1100 there were 54 failures https://ci.ros2.org/view/nightly/job/nightly_win_deb/1100/

## Required Information

* **Job Home**: https://ci.ros2.org/view/nightly/job/nightly_win_deb/
* **First Failing Build** (or oldest one with this issue that you can find): https://ci.ros2.org/view/nightly/job/nightly_win_deb/1100/
* **Latest Failing Build** (try to keep this up to date): https://ci.ros2.org/view/nightly/job/nightly_win_deb/1520/
* **External tracking ticket**: There are so many test failures that it's going to be a lot of work to track them all down

**Comment by emersonknapp** [comment]
This remains true - no plan yet devised

**Comment by thomas-moulard** [comment]
@mjcarroll FYI as you're the current OSRF buildfarmer

**Comment by mjcarroll** [comment]
Tracking issue here: https://github.com/ros2/build_cop/issues/262

I believe that I resolved the debug issues yesterday with the fix outlined in the issue, but it introduced some issues in packaging that I'm now looking into.

**Comment by mjcarroll** [comment]
Just an update on this, the test failures reported here should be largely gone, though I'm still having issues getting a Windows debug build to turn over successfully without hanging on the `ros2*` family of tests.

**Comment by zmichaels11** [comment]
Closing issue out since its tracked twice
