### ISSUE TITLE
Nightly Windows Release build failing rclpy timer test

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-oncall#65]
## Overview

The nightly Windows Release build is failing a specific test suite of rclpy `rclpy.test.test_timer.test_zero_callback[0.01]`

## Required Information

* **Job Home**: https://ci.ros2.org/view/nightly/job/nightly_win_rel/
* **First Failing Build** (or oldest one with this issue that you can find): https://ci.ros2.org/view/nightly/job/nightly_win_rel/1452/
* **Latest Failing Build** (try to keep this up to date): https://ci.ros2.org/view/nightly/job/nightly_win_rel/1452/
* **External tracking ticket**: Not going to create a ticket today - if this doesn't fail tonight then the test is flaky, and if it does fail then it's broken (and maybe flaky) - but either way that will inform the content of the issue created

**Comment by emersonknapp** [comment]
This exact test did not fail last night - seems likely timing is flaky - keeping an eye on it

**Comment by piraka9011** [comment]
Test is no longer failing.
