### ISSUE TITLE
Nightly OSX Release Build FAILED

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-oncall#67]
## Overview

```
00:46:11 [nightly_osx_release] $ /bin/sh -xe /var/folders/0l/mr9y1js52q7fm3mdzzbzfnrw0000gn/T/jenkins8987097548952132578.sh
00:46:11 + rm -rf ws workspace 'work space'
00:46:26 rm: ws/build/rviz_ogre_vendor: Directory not empty
00:46:27 rm: ws/build: Directory not empty
00:46:34 rm: ws: Directory not empty
00:46:34 Build step 'Execute shell' marked build as failure
```

This is confusing and seems like an infrastructure failure.

## Required Information

* **Job Home**: https://ci.ros2.org/view/nightly/job/nightly_osx_release/
* **First Failing Build** (or oldest/old-ish one with this issue that you can find, best effort): https://ci.ros2.org/view/nightly/job/nightly_osx_release/1540/
* **Latest Failing Build** (try to keep this up to date): https://ci.ros2.org/view/nightly/job/nightly_osx_release/1540/
* **External tracking ticket**: Check again after tomorrow's run - we can raise infrastructure issues but they're not best handled via tickets

**Comment by emersonknapp** [comment]
The infrastrucure for OSX is borked across all builds - putting this on hold

**Comment by mjcarroll** [comment]
> The infrastrucure for OSX is borked across all builds - putting this on hold

Tracking here: https://github.com/ros2/build_cop/issues/263

**Comment by dabonnie** [comment]
Failure was resolved in this build: https://ci.ros2.org/view/nightly/job/nightly_osx_release/1551/
