### ISSUE TITLE
Linux armhf packaging job has build warnings in CycloneDDS

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-oncall#68]
## Overview

Two warning types `-Wmissing-prototypes` and `-Wconversion`

## Required Information

* **Job Home**: https://ci.ros2.org/view/packaging/job/packaging_linux-armhf/
* **First Failing Build** (or oldest/old-ish one with this issue that you can find, best effort): https://ci.ros2.org/view/packaging/job/packaging_linux-armhf/290/
* **Latest Failing Build** (try to keep this up to date): https://ci.ros2.org/view/packaging/job/packaging_linux-armhf/330/
* **External tracking ticket**: https://github.com/eclipse-cyclonedds/cyclonedds/issues/388

**Comment by prajakta-gokhale** [comment]
Awaiting approval to contribute to cyclonedds.

**Comment by thomas-moulard** [comment]
Closing as part of ops process changes.
