### ISSUE TITLE
rosbag2_bag_v2 scheduled builds fail

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-oncall#69]
## Overview

catkin_pkg is missing and that's why the builds are failing. We would like them to succeed

## Required Information

* **Job Home**: https://github.com/ros2/rosbag2_bag_v2/actions
* **First Failing Build** (or oldest/old-ish one with this issue that you can find, best effort): all of them
* **Latest Failing Build** (try to keep this up to date): https://github.com/ros2/rosbag2_bag_v2/actions/runs/35987793
* **External tracking ticket**: 
  * [ ] https://github.com/ros2/rosbag2_bag_v2/issues/22
  * [ ] ros-tooling/setup-ros#50

**Comment by zmichaels11** [comment]
Issue opened in https://github.com/ros-tooling/setup-ros/issues/50

**Comment by piraka9011** [comment]
Consider using the tmate action for debug: https://github.com/mxschmitt/action-tmate

**Comment by piraka9011** [comment]
I was able to confirm when ssh'ing into the instance that installing catkin-pkg does resolve the issue when running the ros2 install commands manually.
The issue stems from the `setup-ros` action. `catkin-pkg` properly installs with either `pip3` or `apt`.
However, the command:

```
##[group]Invoking "sudo DEBIAN_FRONTEND=noninteractive RTI_NC_LICENSE_ACCEPTED=yes
apt-get install --no-install-recommends --quiet --yes ros-melodic-desktop"
```

results in uninstalling `catkin-pkg`:

```sh
...
The following packages will be REMOVED:
  python3-catkin-pkg python3-rosdep python3-rosdep-modules python3-rosdistro
  python3-rospkg
```

But the error persists even when installing through pip and apt simultaneously.

**Comment by piraka9011** [comment]
I was able to resolve this by adding a separate step in the workflow that installs `catkin-pkg` from pip after the `setup-ros` step.

**Comment by piraka9011** [comment]
I've found why `catkin-pkg` isn't installing properly.
1. This command is executed to install dependencies:

```sh
sudo DEBIAN_FRONTEND=noninteractive RTI_NC_LICENSE_ACCEPTED=yes
apt-get install --no-install-recommends --quiet --yes
libssl-dev python3-dev build-essential clang cmake git lcov libc++-dev libc++abi-dev
python3-pip python3-rosdep python3-vcstool wget libasio-dev libtinyxml2-dev
libopensplice69 rti-connext-dds-5.3.1
```

It installs `python3-catkin-pkg python3-catkin-pkg-modules`

```sh
...
The following additional packages will be installed:
    cmake-data docutils-common libc++-helpers libc++1 libc++abi1 librhash0
    libtinyxml2-6 python3-catkin-pkg python3-catkin-pkg-modules python3-dateutil
...
```

2. The following command is a pip install which includes `catkin-pkg`:

```sh
sudo pip3 install --upgrade argcomplete catkin-pkg==0.4.16 colcon-bash==0.4.1 ...
```

 however, it assumes it has already been installed by apt:

```sh
Requirement already up-to-date: catkin-pkg==0.4.16 in /usr/lib/python3/dist-packages
```

3. The command after that installs `ros-melodic-desktop` which removes `python3-catkin-pkg`:

```sh
sudo DEBIAN_FRONTEND=noninteractive RTI_NC_LICENSE_ACCEPTED=yes apt-get install --no-install-recommends --quiet --yes ros-melodic-desktop
...
The following packages will be REMOVED:
    python3-catkin-pkg python3-rosdep python3-rosdep-modules python3-rosdistro
    python3-rospkg
```

Unless we add some custom config in setup-ros to catch this edge case, the current solution to get this up and running is to simply install catkin-pkg manually as part of the workflow after setup-ros.

I don't know any other package with such a dependency on ROS1.

**Comment by zmichaels11** [comment]
Would it make sense to allow a custom script to be executed in `setup_ros` ?

**Comment by piraka9011** [comment]
@zmichaels11 I am attempting the solution proposed [here](https://serverfault.com/questions/250224/how-do-i-get-apt-get-to-ignore-some-dependencies/859394)

**Comment by piraka9011** [comment]
Opened ROS Answers [question](https://answers.ros.org/question/345875/installing-ros-melodic-desktop-uninstalls-python3-catkin-pkg/)

**Comment by thomas-moulard** [comment]
Sill failing as of 06/12.
