### ISSUE TITLE
rosbag2_bag_v2 Edev and Ddev bloom builds are failing

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-oncall#70]
## Overview

This package is outputting a CMake warning that ROS1 roscpp can't be found 

## Required Information

* **Job Home**: 
  * http://build.ros2.org/view/Edev/job/Edev__rosbag2_bag_v2__ubuntu_bionic_amd64/
  * http://build.ros2.org/view/Ddev/job/Ddev__rosbag2_bag_v2__ubuntu_bionic_amd64/
* **First Failing Build** (or oldest/old-ish one with this issue that you can find, best effort): since the beginning
* **Latest Failing Build** (try to keep this up to date): 
  * http://build.ros2.org/view/Ddev/job/Ddev__rosbag2_bag_v2__ubuntu_bionic_amd64/11/
  * http://build.ros2.org/view/Edev/job/Edev__rosbag2_bag_v2__ubuntu_bionic_amd64/7/
* **External tracking ticket**: 
  * https://github.com/ros2/rosbag2_bag_v2/issues/13 - this one will actually make these builds into an error, but that would be more informative and move things along

**Comment by prajakta-gokhale** [comment]
The warning has been raised to an error ([commit](https://github.com/ros2/rosbag2_bag_v2/commit/ef48a3ef8a8753b3005862a7c437ff19d70e1745)) and the build is now failing.

**Comment by piraka9011** [comment]
Closing since the infrastructure does not support building ros1 (which is required for this package).
