### ISSUE TITLE
Update On Call Runbook

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-oncall#74]
## Overview

Multiple sections of the on call runbook are now stale. The on call should update the relevant sections to accurately reflect 

## Completion Criteria

 * Identify stale sections
 * Update stale sections
 * Review with stakeholders of sections when appropriate

**Comment by zmichaels11** [comment]
This issue has no exit criteria so I'm unsure how it can be eventually marked as completed.
I gave the On-Call handbook a scan and commented/updated sections that I think need changes

**Comment by zmichaels11** [comment]
This ticket has been through a few on calls as of now so the runbook should be fresh.
