### ISSUE TITLE
Nightly ASan and TSan builds are failing

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros-tooling/aws-oncall#83]
## Overview

One of the builds we care about is not good!

* [x] Add failure type label to this issue (build failure, test failure, build warning)
* [x] Add environment labels to this issue (platform, arch - choose all that apply)
* [x] Please give a one sentence overview of the failure cause we're tracking
* [x] Please title this issue specifically but succinctly

## Required Information

* **Job Home**:
ASan: https://ci.ros2.org/view/nightly/job/nightly_linux_address_sanitizer
TSan: https://ci.ros2.org/view/nightly/job/nightly_linux_thread_sanitizer
* **First Failing Build**
ASan: https://ci.ros2.org/view/nightly/job/nightly_linux_address_sanitizer/324/
TSan: https://ci.ros2.org/view/nightly/job/nightly_linux_thread_sanitizer/334/
* **Latest Failing Build**
ASan: https://ci.ros2.org/view/nightly/job/nightly_linux_address_sanitizer/327/
TSan: https://ci.ros2.org/view/nightly/job/nightly_linux_thread_sanitizer/337/

* **External tracking ticket**: https://github.com/osrf/osrf_testing_tools_cpp/issues/37

Both builds are failing with a linker error when building `osrf_testing_tools_cpp`. The build failures started after a [commit](https://github.com/osrf/osrf_testing_tools_cpp/commit/8fbb6c6a1d0c956f35a29746cbb4c224949aa1a9) in `osrf_testing_tools_cpp`, that bumps up gtest veriosn, was merged.

```bash
--- stderr: osrf_testing_tools_cpp
23:46:34 /usr/bin/ld: ../../googletest-1.8.1-extracted/googletest-1.8.1-build/googlemock/gtest/libgtestd.a(gtest-all.cc.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
23:46:34 //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
23:46:34 collect2: error: ld returned 1 exit status
23:46:34 make[2]: *** [test/test_runner/test_parse_environment_variable] Error 1
23:46:34 make[1]: *** [test/test_runner/CMakeFiles/test_parse_environment_variable.dir/all] Error 2
23:46:34 make[1]: *** Waiting for unfinished jobs....
23:46:34 /usr/bin/ld: ../../googletest-1.8.1-extracted/googletest-1.8.1-build/googlemock/gtest/libgtestd.a(gtest-all.cc.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
23:46:34 //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
23:46:34 collect2: error: ld returned 1 exit status
23:46:34 make[2]: *** [test/test_runner/assert_env_vars] Error 1
23:46:34 make[1]: *** [test/test_runner/CMakeFiles/assert_env_vars.dir/all] Error 2
23:46:34 /usr/bin/ld: ../../googletest-1.8.1-extracted/googletest-1.8.1-build/googlemock/gtest/libgtestd.a(gtest-all.cc.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
23:46:34 //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
23:46:34 collect2: error: ld returned 1 exit status
23:46:34 make[2]: *** [test/memory_tools/test_memory_tools] Error 1
23:46:34 make[1]: *** [test/memory_tools/CMakeFiles/test_memory_tools.dir/all] Error 2
23:46:34 make: *** [all] Error 2
23:46:34 ---
23:46:34 Failed   <<< osrf_testing_tools_cpp	[ Exited with code 2 ]
```

**Comment by prajakta-gokhale** [comment]
The change that caused these failures has been reverted and builds are back to unstable now.

**Comment by piraka9011** [comment]
Builds are now green
