### ISSUE TITLE
All nightly linux jobs have build warnings for test_launch_ros

### ISSUE THREAD

**Issue by piraka9011** [ros-tooling/aws-oncall#89]
## Overview

`test_launch_ros` tests are failing for all nightly linux jobs.

## Required Information

* **Job Home**:
  * https://ci.ros2.org/view/nightly/job/nightly_linux_debug
  * https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug
  * https://ci.ros2.org/view/nightly/job/nightly_linux-armhf_debug/

* **First Failing Build**:
  * https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1461/
  * https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/1097/
  * https://ci.ros2.org/view/nightly/job/nightly_linux-armhf_debug/383/

* **Latest Failing Build** (try to keep this up to date): 
  * https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1479/
  * https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/1125/
  * https://ci.ros2.org/view/nightly/job/nightly_linux-armhf_debug/406/

* **External tracking ticket**: 

[OSRF Buildfarmer is on it](https://github.com/ros2/build_farmer/issues/266)

**Comment by zmichaels11** [comment]
This task was split into individual issues for Debug and Release
