### ISSUE TITLE
OSX Release build is failing

### ISSUE THREAD

**Issue by piraka9011** [ros-tooling/aws-oncall#91]
## Overview

Appears to be a python/venv issue.

## Required Information

* **Job Home**: https://ci.ros2.org/view/nightly/job/nightly_osx_release/
* **First Failing Build**: https://ci.ros2.org/view/nightly/job/nightly_osx_release/1570
* **Latest Failing Build**: https://ci.ros2.org/view/nightly/job/nightly_osx_release/1576 
* **External tracking ticket**:

Will monitor to see if it resolves itself since this is an infra issue that happened before.

**Comment by mm318** [comment]
Build 1663 is now unstable, not failing: https://ci.ros2.org/view/nightly/job/nightly_osx_release/1663/
