### ISSUE TITLE
Windows Release build is unstable

### ISSUE THREAD

**Issue by zmichaels11** [ros-tooling/aws-oncall#95]
## Overview
Windows Release build is unstable.

## Required Information

* **Job Home**: https://ci.ros2.org/view/nightly/job/nightly_win_rel/
* **First Failing Build**: https://ci.ros2.org/view/nightly/job/nightly_win_rel/1474/ 
* **Latest Failing Build**: https://ci.ros2.org/view/nightly/job/nightly_win_rel/1483/
* **External tracking ticket**: There's ~232 test warnings

**Comment by mm318** [comment]
Still unstable with build 1563: https://ci.ros2.org/view/nightly/job/nightly_win_rel/1563/

**Comment by thomas-moulard** [comment]
Closing as part of ops process changes.
