### ISSUE TITLE
Linux x86 Debug has test failures

### ISSUE THREAD

**Issue by zmichaels11** [ros-tooling/aws-oncall#96]
## Required Information

* **Job Home**: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/
* **First Failing Build**: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1486/
* **Latest Failing Build**: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1482/
* **External tracking ticket**: May be related to Issue https://github.com/ros-tooling/aws-oncall/issues/89

**Comment by mm318** [comment]
Still unstable with build 1566: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1566/

**Comment by thomas-moulard** [comment]
Closing as part of ops process changes.
