### ISSUE TITLE
OSX Debug build unstable

### ISSUE THREAD

**Issue by zmichaels11** [ros-tooling/aws-oncall#98]
## Overview
OSX Debug build is possibly unstable, currently listed as aborted

## Required Information
* **Job Home**: https://ci.ros2.org/view/nightly/job/nightly_osx_debug/
* **First Failing Build**: https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1498/
* **Latest Failing Build**: https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1556/
* **External tracking ticket**:

Broke Issue https://github.com/ros-tooling/aws-oncall/issues/13 into Debug (this issue) and Release tickets

**Comment by mm318** [comment]
Still unstable as of build 1641: https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1641/

**Comment by thomas-moulard** [comment]
Closing as part of ops process changes.
